### ISSUE TITLE
"[vehicle] frei" Zeichen (1022/1024) ergänzen

### ISSUE THREAD

**Issue by SupaplexOSM** [wielandb/parking-studio#10]
Wenn das "Hauptzeichen" nicht das blaue P, sondern ein Park-/Halteverbot ist, sind die "... frei" Zeichen (1022 und 1024) als Zusatzzeichen nötig. Sie sind aber noch nicht Teil des Auswahlkatalogs.

Beispiel für eine Schilderkombination: 286 + 1024-10 (Parkverbot, Pkw frei ([Mapillary-Beispiel)](https://www.mapillary.com/app/?pKey=739732783706633))

**Comment by wielandb** [comment]
Eingefügt
