### ISSUE TITLE
Halte- und Parkverbots-restriction hinzufügen, wenn man entsprechende Zeichen in der "physischen" Auswahl auswählt

### ISSUE THREAD

**Issue by SupaplexOSM** [wielandb/parking-studio#4]
In der Auswahl der physischen Parkattribute kann man ja StreetComplete-artig Park- und Halteverbote bzw. nicht vorhandene Parkstreifen auswählen.

Wenn man dabei auf die Halte- oder Parkverbotsschilder klickt (inkl. der Parkverbotszone), sollte zusätzlich zu `parking:_side_=no` auch gleich ein `parking:_side_:restriction=no_parking/no_stopping` mit erscheinen.

**Comment by wielandb** [comment]
Ich würde, ähnlich wie in StreetComplete, im StreetPuzzle wirklich nur die physischen Attribute auswählen lassen wollen, und im SignPuzzle dann die entsprechenden Beschilderungen. Um Verwirrung zu vermeiden, würde ich den Knopf so abändern, dass er keine Zeichen mehr zeigt.
