### ISSUE TITLE
Fix GitHub Link on Website

### ISSUE THREAD

**Issue by SupaplexOSM** [wielandb/parking-studio#6]
It seems there is a small Link to the GitHub page intended at the bottom of the Parking Studio page, but the link refers to Parking Studio itself. So there is no possibility to easy reach the GutHub page from the Website. Maybe you can fix this?

**Comment by wielandb** [comment]
As with #7, when I click the link on the page it redirects to the GitHub page, so it works like intended for me.

I am wondering what may cause theese differences in operation...

**Comment by tordans** [comment]
It works for me as well.

https://wielandb.github.io/parking-studio/export/html5/
<img width="473" alt="image" src="https://user-images.githubusercontent.com/111561/207374116-1dbefd35-2abf-483a-b586-70e86a268d0a.png">

**Comment by tordans** [comment]
It might be a cashing issue. Try a hard reload, Alex. I did not look at the build setup of this too, but if there is no finger printing of files, changed files might still be cached per user.
