### ISSUE TITLE
Neue Zeichenkombination

### ISSUE THREAD

**Issue by SupaplexOSM** [wielandb/parking-studio#7]
Sehr häufig anzutreffen, aber im Tool nicht gültig:

314 + 1040-32 + 1042 (Parken mit Parkscheibe zu bestimmten Zeiten)
```
parking:right:maxstay:conditional=2 hours @ (...)
parking:right:authentication:disc:conditional=yes @ (...)
parking:right:fee=no
```

**Comment by wielandb** [comment]
Sicher? :o 

In den Definitionen [ist es enthalten](https://github.com/wielandb/osm-parking-tagging/blob/3989c7998673e61489d3135dc37c70e9fb94bc7b/export/txt/parking_way.json#L24) und ich kann es im Tool auch auswählen. 

![image](https://user-images.githubusercontent.com/29458682/207369478-6761e9a9-3419-4e13-9c37-a9c4d12e158e.png)

**Comment by SupaplexOSM** [comment]
Äh... Du hast recht... Aber bei mir klappt gerade _gar keine_ Schilderkombination mehr. Irgendetwas ist grundsätzlich kaputt gegangen... Kann ich dir irgendwelche Infos zukommen lassen (außer Ubuntu 18.04 + Firefox 107), um dem auf den Grund zu gehen?

**Comment by SupaplexOSM** [comment]
Ah, ich merke gerade, dass es nur über den Link "https://haukauntrie.de/online/parkingstudio/" nicht geht, den ich mir gebookmarkt habe. Über "https://wielandb.github.io/parking-studio/export/html5/" geht es wie gewohnt.

**Comment by wielandb** [comment]
Oh ja, ich hab die Version auf haukauntrie.de schon länger nicht mehr geupdated. Ich sollte den Link dort besser auch hierher zeigen lassen. 

Technischer Hintergrund: Die Version auf haukauntrie.de unterscheidet immer noch zwischen altem und neuem Tagging, was es im Repo aber bereits nicht mehr gibt, deswegen läuft der Versuch die json abzurufen ins leere, und es gibt gar keine gültigen Kombis.
